---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Check Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
#    branches-ignore: [main] will likely only use main for this project specifically


###############
# Set the Job #
###############
jobs:
#  lint-code:
#    # Name the Job
#    name: Lint Code Base
#    # Set the agent to run on
#    runs-on: ubuntu-latest
#
#    ##################
#    # Load all steps #
#    ##################
#    steps:
#      ##########################
#      # Checkout the code base #
#      ##########################
#      - name: Checkout Code
#        uses: actions/checkout@v2
#        with:
#          # Full git history is needed to get a proper list of changed files within `super-linter`
#          fetch-depth: 0
#
#      ################################
#      # Run Linter against code base #
#      ################################
#      - name: Lint Code Base
#        uses: docker://ghcr.io/github/super-linter:slim-v4
#        env:
#          VALIDATE_ALL_CODEBASE: false
#          DEFAULT_BRANCH: main
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code_coverage:
    name: Test Code
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.9'
      OS: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Generate coverage report
        run: |
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
